[package]
name = "todo_list_v1"
version = "0.1.0"
edition = "2024"
description = "A simple todo list application"
authors = ["Qiqianily <Joedian@163.com>"]
license = "MIT"

[dependencies]
anyhow = "1.0.100"
